# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import models_pb2 as models__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in models_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """Model Service Protocol Buffer definitions

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/proto.ModelService/Chat',
                request_serializer=models__pb2.ChatRequest.SerializeToString,
                response_deserializer=models__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.unary_stream(
                '/proto.ModelService/ChatStream',
                request_serializer=models__pb2.ChatRequest.SerializeToString,
                response_deserializer=models__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/proto.ModelService/ListModels',
                request_serializer=models__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=models__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.GetModelCapabilities = channel.unary_unary(
                '/proto.ModelService/GetModelCapabilities',
                request_serializer=models__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=models__pb2.ModelCapabilities.FromString,
                _registered_method=True)
        self.RegisterPrompt = channel.unary_unary(
                '/proto.ModelService/RegisterPrompt',
                request_serializer=models__pb2.RegisterPromptRequest.SerializeToString,
                response_deserializer=models__pb2.RegisterPromptResponse.FromString,
                _registered_method=True)
        self.GetPrompt = channel.unary_unary(
                '/proto.ModelService/GetPrompt',
                request_serializer=models__pb2.GetPromptRequest.SerializeToString,
                response_deserializer=models__pb2.Prompt.FromString,
                _registered_method=True)
        self.ListPrompts = channel.unary_unary(
                '/proto.ModelService/ListPrompts',
                request_serializer=models__pb2.ListPromptsRequest.SerializeToString,
                response_deserializer=models__pb2.ListPromptsResponse.FromString,
                _registered_method=True)
        self.RegisterModel = channel.unary_unary(
                '/proto.ModelService/RegisterModel',
                request_serializer=models__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=models__pb2.RegisterModelResponse.FromString,
                _registered_method=True)
        self.ListRegisteredModels = channel.unary_unary(
                '/proto.ModelService/ListRegisteredModels',
                request_serializer=models__pb2.ListRegisteredModelsRequest.SerializeToString,
                response_deserializer=models__pb2.ListRegisteredModelsResponse.FromString,
                _registered_method=True)
        self.GetModelStatus = channel.unary_unary(
                '/proto.ModelService/GetModelStatus',
                request_serializer=models__pb2.GetModelStatusRequest.SerializeToString,
                response_deserializer=models__pb2.ModelStatus.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Model Service Protocol Buffer definitions

    """

    def Chat(self, request, context):
        """Core inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPrompt(self, request, context):
        """Prompt management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPrompts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterModel(self, request, context):
        """Custom model registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRegisteredModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=models__pb2.ChatRequest.FromString,
                    response_serializer=models__pb2.ChatResponse.SerializeToString,
            ),
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=models__pb2.ChatRequest.FromString,
                    response_serializer=models__pb2.ChatChunk.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=models__pb2.ListModelsRequest.FromString,
                    response_serializer=models__pb2.ListModelsResponse.SerializeToString,
            ),
            'GetModelCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelCapabilities,
                    request_deserializer=models__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=models__pb2.ModelCapabilities.SerializeToString,
            ),
            'RegisterPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPrompt,
                    request_deserializer=models__pb2.RegisterPromptRequest.FromString,
                    response_serializer=models__pb2.RegisterPromptResponse.SerializeToString,
            ),
            'GetPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrompt,
                    request_deserializer=models__pb2.GetPromptRequest.FromString,
                    response_serializer=models__pb2.Prompt.SerializeToString,
            ),
            'ListPrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPrompts,
                    request_deserializer=models__pb2.ListPromptsRequest.FromString,
                    response_serializer=models__pb2.ListPromptsResponse.SerializeToString,
            ),
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=models__pb2.RegisterModelRequest.FromString,
                    response_serializer=models__pb2.RegisterModelResponse.SerializeToString,
            ),
            'ListRegisteredModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRegisteredModels,
                    request_deserializer=models__pb2.ListRegisteredModelsRequest.FromString,
                    response_serializer=models__pb2.ListRegisteredModelsResponse.SerializeToString,
            ),
            'GetModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStatus,
                    request_deserializer=models__pb2.GetModelStatusRequest.FromString,
                    response_serializer=models__pb2.ModelStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Model Service Protocol Buffer definitions

    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModelService/Chat',
            models__pb2.ChatRequest.SerializeToString,
            models__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.ModelService/ChatStream',
            models__pb2.ChatRequest.SerializeToString,
            models__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModelService/ListModels',
            models__pb2.ListModelsRequest.SerializeToString,
            models__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModelService/GetModelCapabilities',
            models__pb2.GetCapabilitiesRequest.SerializeToString,
            models__pb2.ModelCapabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModelService/RegisterPrompt',
            models__pb2.RegisterPromptRequest.SerializeToString,
            models__pb2.RegisterPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModelService/GetPrompt',
            models__pb2.GetPromptRequest.SerializeToString,
            models__pb2.Prompt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModelService/ListPrompts',
            models__pb2.ListPromptsRequest.SerializeToString,
            models__pb2.ListPromptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModelService/RegisterModel',
            models__pb2.RegisterModelRequest.SerializeToString,
            models__pb2.RegisterModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRegisteredModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModelService/ListRegisteredModels',
            models__pb2.ListRegisteredModelsRequest.SerializeToString,
            models__pb2.ListRegisteredModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ModelService/GetModelStatus',
            models__pb2.GetModelStatusRequest.SerializeToString,
            models__pb2.ModelStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
